---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: scripts/init_kickstart.sh
  label: Init_kickstart.sh
- type: document
  path: data/page_sharer.toml
  label: Page_Sharer
- type: directory
  path: data/themes
  label: themes
  create: all
  match: "**/*"
- type: directory
  path: data/fonts
  label: Fonts
  create: all
  match: "**/*"
- type: directory
  path: content/talk
  label: Talk
  create: all
  match: "**/*"
- type: directory
  path: content/publication
  label: Publication
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: document
  path: config/_default/menus.toml
  label: Menus.toml
- type: document
  path: config/_default/params.toml
  label: 'Params.toml '
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: config/_default/content
  label: Pages
  create: all
  match: "*"
upload_dir: config/_default/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
